.TH VGRIND 1 ДЕМОС/PV
.SH ИМЯ
.B vgrind
\- выдать размеченный листинг программы.
.SH ФОРМАТ
.B vgrind
.RB [-f]
.RB [-]
.RB [-t]
.RB [-n]
.RB [-x]
.RB [-W]
.RB [-sn]
.RB [-u]
.RB [-h \fIheader\fR]
.RB [-d \fIDescriptionFile\fR]
.RB [-l \fIlanguage\fR]
.I  name ...
.SH ОПИСАНИЕ
.B vgrind
форматирует исходные тексты программ, указанных в аргументах,
используя разные шрифты и выделения. Собственно форматирование выполняет
программа
.B nroff(1).
Комментарии и строки выделяются курсивом,
ключевые слова - полужирным шрифтом,
у правого края каждой страницы печатается имя текущей функции.
.PP
.B vgrind
работает в 2х базовых режимах - режиме фильтра и регулярном.
.PP
В режиме фильтра
.B vgrind
работает как программа-фильтр, наподобие
.B tbl(1).
Стандартный ввод направляется сразу же в стандартный вывод,
за исключением строк, заключенных в директивы
.B nroff
.IP .vS
начать обработку
.IP .vE
завершить обработку
.PP
Такие строки форматируются как было описано выше.
Вывод фильтра должен быть направлен на вход программы
.B nroff(1).
.PP
В регулярном режиме
.B vgrind
обрабатывает входные файлы и передает их
.B nroff-у
для вывода.
.PP
В обоих режимах
.B vgrind
пропускает все строки, начинающиеся с точки без какой-либо
обработки.
.SH ФЛАГИ
.IP "\fB-f\fR"
включает режим фильтра.
.IP "\fB-\fR"
ввод должен подаваться со стандартного ввода.
(по умолчанию - если указан флаг \fB-f\fR).
.IP "\fB-n\fR"
отменяет выделение ключевых слов жирным шрифтом.
.IP "\fB-u\fR"
отменяет выделение строк курсивом.
.IP "\fB-x\fR"
создать файл оглавления. Чтобы сделать это, необходимо
создать пустой файл
.I index
в текущем каталоге.
При запуске
.B vgrind
файл
.I index
будет автоматически составлен заново.
Затем оглавление определений функций можно создать,
запустив команду
.B vgrind\ -x
указав файл
.I index
как аргумент.
.IP "\fB-W\fR"
указывает вывод на  широкий принтер
\fIVersatec\fR.
.IP "\fB-s\fR"
задает ширину точки при выводе
(точно как директива \fB.ps\fR)
.IP "\fB-h\fR"
задает заголовок страниц листинга
(по умолчанию - имя файла).
.IP "\fB-d\fR"
задает файл с определениями для языка
(по умолчанию \fI/usr/ucb/lib/vgrindefs\fR).
.IP "\fB-l\fR"
задает язык.
В настоящее время есть описания для
.B C (-lc),
.B PASCAL (-lp),
.B SH (-lsh),
.B CSH (-lcsh)
.SH ФАЙЛЫ
.IP \fIindex\fR
файл оглавления
.IP \fI/usr/lib/tmac/tmac.vgrind\fR
макропакет для \fBnroff\fR
.IP \fI/usr/ucb/lib/vfontedpr\fR
фильтр-препроцессор
.IP \fI/usr/ucb/lib/vgrindefs\fR
описание языков программирования
.SH "ДОПОЛНИТЕЛЬНЫЕ ССЫЛКИ"
.B nroff(1), vgrindefs(5)
.SH ЗАМЕЧАНИЯ
Формат процедуры должен быть таков:
.ES L
    \fIСтрока, удовлетворяющая описателю начала
    процедуры \fB<pb>\fR
    \fIНачало блока \fB<bb>\fR
     ...
    \fIКонец блока \fB<be>\fR
.EE
.PP
Появление комментария между первой строкой и началом блока
может привести к странным результатам.
