#! /bin/sh
# $Header: /usr/users/korotay/DEMOS_2.2/rcs/src/rcs/RCS/merge,v 1.4 1988/11/18 21:55:57 dvolodin Exp $
#
# Слияние версий файлов.
#
# Использование: merge [-p] файл1 файл2 файл3 [mark1 mark3]
#
# Результат: все редакции, необходимые для перевода файла2 в файл3,
# проводятся над файлом1. Если задан ключ -p, результат передается
# в стандартный файл вывода (файл1 не переписывается).
#
# Пересечение редакций отмечается следующим образом:
#
#                <<<<<<< file1
#                строки файла1
#                =======
#                строки файла3
#                >>>>>>> file3
#
# Если заданы параметры mark1 и mark3, они подставляются
# в строках-разделителях <<<<.. и >>>>... вместо имен файл1 и файл3.
# При перекрытии редакций, выдается предупредительное сообщение.

PATH=.:/usr/bin:/usr/ucb
DIFF3=$HOME/d22/lib/rcs/rdiff3
p=0
case $1 in
-p)
	p=$1
	shift;;
esac


if test $# -ge 3
then
	if test -f $1 -a -f $2 -a -f $3
	then
		trap "rm -f /tmp/d3[abc]$$" 0 1 2 13 15
		diff $1 $3 >/tmp/d3a$$
		diff $2 $3 >/tmp/d3b$$
		$DIFF3 -E /tmp/d3[ab]$$ $1 $2 $3 $4 $5 > /tmp/d3c$$
		r=$?
		if test $r != 0
		then
			case ${MSG=e} in
			r) echo Предупреждение: $r вернул ненулевой код. 1>&2 ;;
			*) echo Warning: $r overlaps during merge. 1>&2 ;;
			esac
		fi
		if test $p != 0
		then
			(cat /tmp/d3c$$; echo '1,$p') | ed - $1
		else
			(cat /tmp/d3c$$; echo w) | ed - $1
		fi
		exit 0
	else
		case ${MSG=e} in
		r) echo "Не могу открыть $1, $2 или $3" 1>&2 ;;
		*) echo "Cannot open $1, $2, or $3" 1>&2 ;;
		esac
	fi
fi
case ${MSG=e} in
r) echo "Вызов: merge [-p] файл1 файл2 файл3" 1>&2 ;;
*) echo "Usage: merge [-p] file1 file2 file3" 1>&2 ;;
esac
exit 1
